---
- name: Check Nginx status
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Retrieve service facts
      service_facts:

    - name: Display Nginx status
      debug:
        var: ansible_facts.services['nginx'].state
