---
- hosts: localhost  # you can enter any host you want
  become: true
  tasks:

  - name: restart server
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true
